---
functional:
  - Пользователь должен иметь возможность создания пробной игры без регистрации/авторизации
  - Пользователь должен иметь возможность регистрации через email
  - Пользователь должен иметь возможность авторизации через github
  - Пользователь должен иметь возможность авторизации через discord
  - Пользователь должен иметь возможность восстановить пароль
  - Пользователь должен иметь возможность создания и настройки игры (сложность, тип игры, таймер, название, теги)
  - Пользователь должен иметь возможность открыть гайд с описанием функционала в созданной игре (Show guide)
  - Пользователь должен иметь возможность выбора языка описания задания игры (русский, английский)
  - Пользователь должен иметь возможность выбора языка программирования в игре
  - Пользователь должен иметь возможность проверить собственное решение неограниченное количество раз
  - Пользователь должен иметь возможность возвращения в игру после вылета из неё
  - Пользователь должен иметь возможность написания кода в текстовом редакторе игры
  - Пользователь должен иметь возможность сбросить все изменения кода (Resert solution)
  - Пользователь должен иметь возможность запуска написанного кода (Run)
  - Пользователь должен иметь возможность отправлять сообщения в чат игры
  - Пользователь должен иметь возможность вернуться на главную страницу сайта без прерывания игры
  - Пользователь должен иметь возможность произвести рематч после окончания времени по таймеру
  - Пользователь должен иметь возможность сдаться во время игры (Give up)
  - Пользователь должен иметь возможность просматривать рейтинг игроков в LEADERBOARD
  - Пользователь должен иметь возможность присоединиться к просмотру турнира других игроков
  - Пользователь должен иметь возможность присоединения к турниру в качестве второго игрока
  - Пользователь должен иметь возможность отправки сообщений в чат на главной странице сайта
  - Пользователь должен видеть модальное с анимацией окно в случае выигрыша/проигрыша
  - Пользователь-победитель должен иметь возможность выхода из игры
  - Пользователь-проигравший должен иметь возможность доиграть до конца
  - Игры считается полностью законченной после выхода обоих игроков
  - Пользователь должен иметь возможность просмотра личного рейтинга
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Пользователь должен иметь личный кабинет на сайте
  - Пользователь должен иметь возможность просмотра истории в игре
  - Пользователь должен слышать звуковые эффекты при победе/проигрыше
  - Пользователь должен иметь возможность настраивать звуковые эффекты, выбирать дневную/ночную тему, изменять никнейм
  - Никнейм должен содержать от 3 до 16 символов
  - Никнейм может содержать латиницу, цифры, нижнее подчёркивание
