---
functional:
  - Пользователь должен иметь возможность создания пробной игры без регистрации/авторизации
  - Пользователь должен иметь возможность регистрации через email
  - Пользователь должен иметь возможность авторизации через github/discord
  - Пользователь должен иметь возможность восстановить пароль
  - Пользователь должен иметь возможность создания и настройки игры (сложность, тип игры, таймер, название, теги)
  - Пользователь должен иметь возможность открыть гайд с описанием функционала в созданной игре (Show guide)
  - Пользователь должен иметь возможность выбора языка описания задания игры (русский, английский)
  - Пользователь должен иметь возможность выбора языка программирования в игре
  - Пользователь должен иметь возможность проверить собственне решение неограниченное количество раз
  - Пользователь должен иметь возможность возвращения в игру после вылета из неё
  - Пользователь должен иметь возможность написания кода в текстовом редакторе игры
  - Пользователь должен иметь возможность перезагрузки решения (Resert solution)
  - Пользователь должен иметь возможность запуска написанного кода (Run)
  - Пользователь должен иметь возможность оставять сообщений в чате во время игры
  - Пользователь должен иметь возможность вернуться на главную страницу без выхода из игры
  - Пользователь должен иметь возможность вернуться в игру с главной страницы
  - Пользователь должен иметь возможность произвести рематч после окончания времени по таймеру
  - Пользователь должен иметь возможность сдаться (Give up)
  -  Пользователь должен иметь возможность просмотривать рейтинг игроков
  - Пользователь должен иметь возможность просмотра турниров (TOURNMATES)
  - Пользователь должен иметь возможность просматриать LOBBY
  - Пользователь lолжен видеть модальное окно в случае выигрыша/проигрыша
  - Пользователь-победитель должен иметь возможность выхода из игры (Exit)
  - Пользователь-проигравший должен иметь возможность доиграть до конца
  - Игры считается полностью законченной после выхода обоих игроков
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь личный кабинет на сайте
  - Пользователь должен иметь возможность выбора дневной\ночной темы
  - Пользователь должен иметь возможность просмотра личного рейтинга в игре
  - Пользователь должен иметь возможность просмотра истории в игре
  - Пользователь должен видеть анимацию при победе/проигрыше
  - Пользователь должен слышать звуковые эффекты при победе/проигрыше
  - Пользователь должен иметь возможность настраивать звуковые эффекты, выбирать днейвную/ночную тему, изменять никнейм
  - Никнейм должен содержать от 3 до 16 символов
  - Никнейм может содержать латиницу, цифры, нижнее подчёркивание
